name: 🌈 All Builds
on:
  push:
    branches: [ godot-4.x ]
    tags:
      - "v2*"
  pull_request:
    branches: "*"

# Global Settings
env:
  PROJECT_FOLDER: fmod-gdnative
  TARGET_PATH: demo/addons/fmod/libs/
  TARGET_NAME: libGodotFmod
  TARGET: editor
  GODOT_VERSION: 4.1.1
  FMOD_VERSION: 20212

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows Compilation
            os: "windows-2022"
            platform: windows
            artifact-extension: dll
            additional-python-packages: pywin32
            fmod-executable-suffix: win-installer.exe
            shell: pwsh

          - name: Ubuntu Compilation
            os: "ubuntu-20.04"
            platform: linux
            artifact-extension: so
            fmod-executable-suffix: linux.tar.gz
            shell: bash

          - name: MacOS Compilation
            os: "macos-11"
            platform: macos
            artifact-extension: framework
            fmod-executable-suffix: osx.dmg
            shell: bash

          - name: Android Compilation
            os: "ubuntu-20.04"
            platform: android
            artifact-extension: so
            fmod-executable-suffix: android.tar.gz
            flags: ANDROID_NDK_ROOT=$ANDROID_NDK_LATEST_HOME arch=arm64
            shell: bash

          - name: iOS Compilation
            os: "macos-11"
            platform: ios
            artifact-extension: dylib
            fmod-executable-suffix: ios.dmg
            flags: arch=arm64
            shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
          submodules: recursive

      - name: Compile native plugin
        uses: ./.github/actions/create-native-build
        with:
          platform: ${{ matrix.platform }}
          target: ${{ env.TARGET }}
          artifact-extension: ${{ matrix.artifact-extension }}
          additional-python-packages: ${{ matrix.additional-python-packages }}
          flags: ${{ matrix.flags }}
          fmod-executable-suffix: ${{ matrix.fmod-executable-suffix }}
          fmod-user: ${{ secrets.FMODUSER }}
          fmod-password: ${{ secrets.FMODPASS }}
          shell: ${{ matrix.shell }}

      - name: Set up JDK 17
        if: matrix.platform == 'android'
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Copy android fmod jar
        if: matrix.platform == 'android'
        run: |
          mkdir -p android-plugin/library/libraries/android/aar/
          cp ../libs/fmod/android/core/lib/fmod.jar android-plugin/library/libraries/fmod.jar

      - name: Download godot android aar
        if: matrix.platform == 'android'
        run : |
          cd android-plugin/library/libraries/
          wget https://github.com/godotengine/godot/releases/download/${{ env.GODOT_VERSION }}-stable/godot-lib.${{ env.GODOT_VERSION }}.stable.template_release.aar

      - name: Build android plugin
        if: matrix.platform == 'android'
        uses: eskatos/gradle-command-action@v1
        with:
          wrapper-directory: android-plugin/
          build-root-directory: android-plugin/
          arguments: :library:build